name: prog_news
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HindMysuru
      fonts:
        - asset: assets/fonts/HindMysuru-Bold.ttf
        - asset: assets/fonts/HindMysuru-Light.ttf
        - asset: assets/fonts/HindMysuru-Medium.ttf
        - asset: assets/fonts/HindMysuru-Regular.ttf
        - asset: assets/fonts/HindMysuru-SemiBold.ttf
