name: prog_news
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7
  iconsax: ^0.0.8
  intl: ^0.20.1
  line_icons: ^2.0.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HindMysuru
      fonts:
        - asset: assets/fonts/HindMysuru-Bold.ttf
        - asset: assets/fonts/HindMysuru-Light.ttf
        - asset: assets/fonts/HindMysuru-Medium.ttf
        - asset: assets/fonts/HindMysuru-Regular.ttf
        - asset: assets/fonts/HindMysuru-SemiBold.ttf
